apiVersion: apps/v1
kind: Deployment
metadata:
    name: web
    annotations:
        git.tag: 1.0.0
    labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/version: 1.0.0
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: web
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    template:
        metadata:
            labels:
                app.kubernetes.io/name: web
                app.kubernetes.io/version: 1.0.0
        spec:
            containers:
                - name: web
                  image: nonnemacher/web:1.0.0
                  imagePullPolicy: Always
                  ports:
                      - name: http
                        containerPort: 80
                        protocol: TCP
                  livenessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /info
                          port: http
                          scheme: HTTP
                      initialDelaySeconds: 5
                      periodSeconds: 20
                      successThreshold: 1
                      timeoutSeconds: 3
                  readinessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /info
                          port: http
                          scheme: HTTP
                      initialDelaySeconds: 5
                      periodSeconds: 10
                      successThreshold: 1
                      timeoutSeconds: 3
                  resources:
                      limits:
                          memory: 20Mi
                          cpu: 500m                      