apiVersion: v1
kind: Service
metadata:
    name: web
    labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/version: 1.0.0
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: http
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: web
